accounts/urls.py
from django.urls import path
from . import views 

app_name = 'accounts'

urlpatterns = [
    path('sign-in/', views.sign_in, name='sign_in'),
    path('sign-up/', views.sign_up, name='sign_up'), 
]

little_fasion/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('web.urls',)),
    path('', include('products.urls',)),
    path('', include('accounts.urls',)),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from . import views

app_name = 'products'

urlpatterns = [
    path('detail/', views.product_detail, name='product_detail'),
    path('products/', views.products, name='products'),
]

web/urls.py
from django.urls import path
from . import views

app_name = 'web'       # registering web in url    used when include is used in main url 

urlpatterns = [
    path('', views.index, name='index'),
    path('story/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),                  #name is used to get from html page
    path('faq/', views.faq, name='faq'), 
    path('contact-submit/', views.contact_view, name='contact_form')
]

products/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _                    # _ in verbose


class Product(models.Model):
    image = models.ImageField(upload_to='media')
    name = models.CharField(max_length=250)
    description = models.TextField()
    price = models.CharField(max_length=250, null=True, blank=True)
    created_date = models.DateField(null=True, blank=True)
    is_popular = models.BooleanField(default=False)
    is_trending = models.BooleanField(default=False)
    new_arrival = models.BooleanField(default=False)
    discounted_price = models.BooleanField(default=False)
    order_id = models.PositiveIntegerField(blank=True, null=True)
    
    class Meta:
        db_table = 'fasion_product'
        verbose_name = _('Product')
        verbose_name_plural = _('Products')
        ordering = ('-id', )
    
    def __str__(self):
        return f"{self.name}"

products/views.py
from django.shortcuts import render
from .models import Product
import datetime

def product_detail(request):
    return render(request, 'product-detail.html')

def products(request):
    products = Product.objects.all().order_by('order_id')
    new_products = products.filter(created_date__month=datetime.datetime.now().month, created_date__year=datetime.datetime.now().year )
    popular_products = products.filter(is_popular=True)
    context = {
       'products' : products,
       'new_products' : new_products,
       'popular_products' : popular_products
    }
    
    return render(request, 'products.html', context)

templates/contact.html
<!doctype html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <meta name="description" content="">
        <meta name="author" content="">

        <title>Tooplate's Little Fashion - Contact Page</title>

        <!-- CSS FILES -->
        <link rel="preconnect" href="https://fonts.googleapis.com">

        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>

        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@100;300;400;700;900&display=swap" rel="stylesheet">

        <link href="{% static 'css/bootstrap.min.css'%}" rel="stylesheet">
        <link href="{% static 'css/bootstrap-icons.css'%}" rel="stylesheet">

        <link rel="stylesheet" href="{% static 'css/slick.css'%}"/>

        <link href="{% static 'css/tooplate-little-fashion.css'%}" rel="stylesheet">
        
<!--

Tooplate 2127 Little Fashion

https://www.tooplate.com/view/2127-little-fashion

-->
    </head>
    
    <body>

        <section class="preloader">
            <div class="spinner">
                <span class="sk-inner-circle"></span>
            </div>
        </section>
    
        <main>

            <nav class="navbar navbar-expand-lg">
                <div class="container">
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                    <a class="navbar-brand" href="{% url 'web:index'%}">
                        <strong><span>Little</span> Fashion</strong>
                    </a>

                    <div class="d-lg-none">
                        <a href="{% url 'accounts:sign_in'%}"  class="bi-person custom-icon me-3"></a>

                        <a href="{% url 'products:product_detail'%}" class="bi-bag custom-icon"></a>
                    </div>

                    <div class="collapse navbar-collapse" id="navbarNav">
                        <ul class="navbar-nav mx-auto">
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'web:index'%}" >Home</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'web:about'%}">Story</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'products:products'%}">Products</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'web:faq'%}">FAQs</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link active" href="{% url 'web:contact'%}">Contact</a>
                            </li>
                        </ul>

                        <div class="d-none d-lg-block">
                            <a href="{% url 'accounts:sign_in'%}" class="bi-person custom-icon me-3"></a>

                            <a href="{% url 'products:product_detail'%}" class="bi-bag custom-icon"></a>
                        </div>
                    </div>
                </div>
            </nav>

            <header class="site-header section-padding-img site-header-image">
                <div class="container">
                    <div class="row">

                        <div class="col-lg-10 col-12 header-info">
                            <h1>
                                <span class="d-block text-primary">Say hello to us</span>
                                <span class="d-block text-dark">love to hear you</span>
                            </h1>
                        </div>
                    </div>
                </div>

                <img src="{% static 'images/header/positive-european-woman-has-break-after-work.jpg'%}" class="header-image img-fluid" alt="">
            </header>

            <section class="contact section-padding">
                <div class="container">
                    <div class="row">
                        
                        <div class="col-lg-6 col-12">
                            <h2 class="mb-4">Let's <span>begin</span></h2>

<!-- contact form  -->

                            <form action="{% url 'web:contact_form' %}" method="post" role="form">
                                {% csrf_token %}
                                    <div class="form-floating">
                                        <!-- <input type="text" name="name" id="name" class="form-control" placeholder="Full name" required> -->
                                        {{ form.name }}
                                        <label for="name">Full name</label>
                                    </div>

                                    <div class="form-floating my-4">
                                        <!-- <input type="email" name="email" id="email" pattern="[^ @]*@[^ @]*" class="form-control" placeholder="Email address" required> -->
                                        {{ form.email }}
                                        <label for="email">Email address</label>
                                    </div>
                                    
                                    <div class="form-floating my-4">
                                        <!-- <input type="subject" name="subject" id="subject"class="form-control" placeholder="Subject" required> -->
                                        {{ form.subject }}
                                        <label for="subject">Subject</label>
                                    </div>

                                    <div class="form-floating mb-4" >
                                        <!-- <textarea id="message" name="detail" class="form-control" placeholder="Leave a comment here" required style="height: 160px"></textarea> -->
                                        {{ form.detail }}
                                        <label for="message">Tell us about the project</label>
                                    </div>

                                    <div class="col-lg-5 col-6">
                                        <button type="submit" class="form-control">Send</button>
                                    </div>
                            </form>
                        </div>

                        <div class="col-lg-6 col-12 mt-5 ms-auto">
                            <div class="row">
                                <div class="col-6 border-end contact-info">
                                    <h6 class="mb-3">New Business</h6>

                                    <a href="mailto:hello@company.com" class="custom-link">
                                        hello@company.com
                                        <i class="bi-arrow-right ms-2"></i>
                                    </a>
                                </div>

                                <div class="col-6 contact-info">
                                	<h6 class="mb-3">Main Studio</h6>

                                    <a href="mailto:studio@company.com" class="custom-link">
                                        studio@company.com
                                        <i class="bi-arrow-right ms-2"></i>
                                    </a>
                                </div>

                                <div class="col-6 border-top border-end contact-info">
                                    <h6 class="mb-3">Our Office</h6>

                                    <p class="text-muted">Akershusstranda 20, 0150 Oslo, Norway</p>
                                </div>

                                <div class="col-6 border-top contact-info">
                                    <h6 class="mb-3">Our Socials</h6>

                                    <ul class="social-icon">

                                        <li><a href="#" class="social-icon-link bi-messenger"></a></li>

                                        <li><a href="#" class="social-icon-link bi-youtube"></a></li>

                                        <li><a href="#" class="social-icon-link bi-instagram"></a></li>

                                        <li><a href="#" class="social-icon-link bi-whatsapp"></a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </section>
        </main>

        <footer class="site-footer">
            <div class="container">
                <div class="row">

                    <div class="col-lg-3 col-10 me-auto mb-4">
                        <h4 class="text-white mb-3"><a href="{% url 'web:index'%}">Little</a> Fashion</h4>
                        <p class="copyright-text text-muted mt-lg-5 mb-4 mb-lg-0">Copyright © 2022 <strong>Little Fashion</strong></p>
                        <br>
                        <p class="copyright-text">Designed by <a href="https://www.tooplate.com/" target="_blank">Tooplate</a></p>
                    </div>

                    <div class="col-lg-5 col-8">
                        <h5 class="text-white mb-3">Sitemap</h5>

                        <ul class="footer-menu d-flex flex-wrap">
                            <li class="footer-menu-item"><a href="{% url 'web:about'%}" class="footer-menu-link">Story</a></li>

                            <li class="footer-menu-item"><a href="#" class="footer-menu-link">Products</a></li>

                            <li class="footer-menu-item"><a href="#" class="footer-menu-link">Privacy policy</a></li>

                            <li class="footer-menu-item"><a href="#" class="footer-menu-link">FAQs</a></li>

                            <li class="footer-menu-item"><a href="#" class="footer-menu-link">Contact</a></li>
                        </ul>
                    </div>

                    <div class="col-lg-3 col-4">
                        <h5 class="text-white mb-3">Social</h5>

                        <ul class="social-icon">

                            <li><a href="#" class="social-icon-link bi-youtube"></a></li>

                            <li><a href="#" class="social-icon-link bi-whatsapp"></a></li>

                            <li><a href="#" class="social-icon-link bi-instagram"></a></li>

                            <li><a href="#" class="social-icon-link bi-skype"></a></li>
                        </ul>
                    </div>

                </div>
            </div>
        </footer>

        <!-- JAVASCRIPT FILES -->
        <script src="{% static 'js/jquery.min.js'%}"></script>
        <script src="{% static 'js/bootstrap.bundle.min.js'%}"></script>
        <script src="{% static 'js/Headroom.js'%}"></script>
        <script src="{% static 'js/jQuery.headroom.js'%}"></script>
        <script src="{% static 'js/slick.min.js'%}"></script>
        <script src="{% static 'js/custom.js'%}"></script>

    </body>
</html>

templates/faq.html
<!doctype html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <meta name="description" content="">
        <meta name="author" content="">

        <title>Tooplate's Little Fashion - FAQs Page</title>

        <!-- CSS FILES -->
        <link rel="preconnect" href="https://fonts.googleapis.com">

        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>

        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@100;300;400;700;900&display=swap" rel="stylesheet">

        <link href="{% static 'css/bootstrap.min.css'%}" rel="stylesheet">
        <link href="{% static 'css/bootstrap-icons.css'%}" rel="stylesheet">

        <link rel="stylesheet" href="{% static 'css/slick.css'%}"/>

        <link href="{% static 'css/tooplate-little-fashion.css'%}" rel="stylesheet">
        
<!--

Tooplate 2127 Little Fashion

https://www.tooplate.com/view/2127-little-fashion

-->
    </head>
    
    <body>

        <section class="preloader">
            <div class="spinner">
                <span class="sk-inner-circle"></span>
            </div>
        </section>
    
        <main>

            <nav class="navbar navbar-expand-lg">
                <div class="container">
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                    <a class="navbar-brand" href="{% url 'web:index'%}">
                        <strong><span>Little</span> Fashion</strong>
                    </a>

                    <div class="d-lg-none">
                        <a href="{% url 'accounts:sign_in'%}"  class="bi-person custom-icon me-3"></a>

                        <a href="{% url 'products:product_detail'%}" class="bi-bag custom-icon"></a>
                    </div>

                    <div class="collapse navbar-collapse" id="navbarNav">
                        <ul class="navbar-nav mx-auto">
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'web:index'%}" >Home</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'web:about'%}">Story</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'products:products'%}">Products</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link active" href="{% url 'web:faq'%}">FAQs</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'web:contact'%}">Contact</a>
                            </li>
                        </ul>

                        <div class="d-none d-lg-block">
                            <a href="{% url 'accounts:sign_in'%}" class="bi-person custom-icon me-3"></a>

                            <a href="{% url 'products:product_detail'%}" class="bi-bag custom-icon"></a>
                        </div>
                    </div>
                </div>
            </nav>

            <header class="site-header section-padding d-flex justify-content-center align-items-center">
                <div class="container">
                    <div class="row">

                        <div class="col-lg-10 col-12">
                            <h1>
                                <span class="d-block text-primary">Your favorite questions</span>
                                <span class="d-block text-dark">and our answers to them</span>
                            </h1>
                        </div>
                    </div>
                </div>
            </header>

            <section class="faq section-padding">
                <div class="container">
                    <div class="row">
                        
                        <div class="col-lg-8 col-12">
                            <h2>General Info.</h2>

                            <div class="accordion" id="accordionGeneral">
                                <div class="accordion-item">
                                    <h2 class="accordion-header" id="headingOne">
                                        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#accordionGeneralOne" aria-expanded="true" aria-controls="accordionGeneralOne">
                                        What is this Little Fashion?
                                        </button>
                                    </h2>

                                    <div id="accordionGeneralOne" class="accordion-collapse collapse" aria-labelledby="headingOne" data-bs-parent="#accordionGeneral">

                                        <div class="accordion-body">
                                            <p class="large-paragraph"><strong>Little Fashion</strong> is free Bootstrap 5 website template for everyone. There are 8 HTML pages included in this template and you can expand more pages as you need.</p>

                                            <p class="large-paragraph">Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
                                        </div>
                                    </div>
                                </div>

                                <div class="accordion-item">
                                    <h2 class="accordion-header" id="headingTwo">
                                        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#accordionGeneralTwo" aria-expanded="false" aria-controls="accordionGeneralTwo">
                                        What is Tooplate website?
                                        </button>
                                    </h2>

                                    <div id="accordionGeneralTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionGeneral">

                                        <div class="accordion-body">
                                            <p class="large-paragraph"><a href="https://www.tooplate.com/free-templates" target="_blank">Tooplate</a> is a great website to download free HTML website templates for your business or personal use. Tooplate website has been online for almost 8 years now. Thank you for visiting our website.</p>
                                        </div>
                                    </div>
                                </div>

                                <div class="accordion-item">
                                    <h2 class="accordion-header" id="headingThree">
                                        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#accordionGeneralThree" aria-expanded="false" aria-controls="accordionGeneralThree">
                                        How do I support your website?
                                        </button>
                                    </h2>

                                    <div id="accordionGeneralThree" class="accordion-collapse collapse" aria-labelledby="headingThree" data-bs-parent="#accordionGeneral">

                                        <div class="accordion-body">
                                            <p class="large-paragraph">You can support our Tooplate website by sharing it to your friends or colleagues on the web or social media.</p>
                                        </div>
                                    </div>
                                </div>

                            </div>

                            <h2 class="mt-5">About <span>our products</span></h2>

                            <div class="accordion" id="accordionProduct">
                                <div class="accordion-item">
                                    <h2 class="accordion-header" id="headingFour">
                                        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#accordionProductOne" aria-expanded="true" aria-controls="accordionProductOne">
                                        What is Fashion Design?
                                        </button>
                                    </h2>

                                    <div id="accordionProductOne" class="accordion-collapse collapse" aria-labelledby="headingFour" data-bs-parent="#accordionProduct">

                                        <div class="accordion-body">
                                            <p class="large-paragraph"><strong>Lorem ipsum dolor</strong> sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quis ipsum suspendisse ultrices gravida. Risus commodo viverra maecenas accumsan lacus vel facilisis.</p>

                                            <p class="large-paragraph">Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
                                        </div>
                                    </div>
                                </div>

                                <div class="accordion-item">
                                    <h2 class="accordion-header" id="headingFive">
                                        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#accordionProductTwo" aria-expanded="false" aria-controls="accordionProductTwo">
                                        How do I use the product?
                                        </button>
                                    </h2>

                                    <div id="accordionProductTwo" class="accordion-collapse collapse" aria-labelledby="headingFive" data-bs-parent="#accordionProduct">

                                        <div class="accordion-body">
                                            <p class="large-paragraph">Lorem ipsum is placeholder text commonly used in the graphic, print, and publishing industries for previewing layouts and visual mockups.</p>
                                        </div>
                                    </div>
                                </div>

                            </div>

                        </div>

                    </div>
                </div>
            </section>

        </main>

        <footer class="site-footer">
            <div class="container">
                <div class="row">

                    <div class="col-lg-3 col-10 me-auto mb-4">
                        <h4 class="text-white mb-3"><a href="{% url 'web:index'%}">Little</a> Fashion</h4>
                        <p class="copyright-text text-muted mt-lg-5 mb-4 mb-lg-0">Copyright © 2022 <strong>Little Fashion</strong></p>
                        <br>
                        <p class="copyright-text">Designed by <a href="https://www.tooplate.com/" target="_blank">Tooplate</a></p>
                    </div>

                    <div class="col-lg-5 col-8">
                        <h5 class="text-white mb-3">Sitemap</h5>

                        <ul class="footer-menu d-flex flex-wrap">
                            <li class="footer-menu-item"><a href="{% url 'web:about'%}" class="footer-menu-link">Story</a></li>

                            <li class="footer-menu-item"><a href="#" class="footer-menu-link">Products</a></li>

                            <li class="footer-menu-item"><a href="#" class="footer-menu-link">Privacy policy</a></li>

                            <li class="footer-menu-item"><a href="#" class="footer-menu-link">FAQs</a></li>

                            <li class="footer-menu-item"><a href="#" class="footer-menu-link">Contact</a></li>
                        </ul>
                    </div>

                    <div class="col-lg-3 col-4">
                        <h5 class="text-white mb-3">Social</h5>

                        <ul class="social-icon">

                            <li><a href="#" class="social-icon-link bi-youtube"></a></li>

                            <li><a href="#" class="social-icon-link bi-whatsapp"></a></li>

                            <li><a href="#" class="social-icon-link bi-instagram"></a></li>

                            <li><a href="#" class="social-icon-link bi-skype"></a></li>
                        </ul>
                    </div>

                </div>
            </div>
        </footer>

        <!-- JAVASCRIPT FILES -->
        <script src="{% static 'js/jquery.min.js'%}"></script>
        <script src="{% static 'js/bootstrap.bundle.min.js'%}"></script>
        <script src="{% static 'js/Headroom.js'%}"></script>
        <script src="{% static 'js/jQuery.headroom.js'%}"></script>
        <script src="{% static 'js/slick.min.js'%}"></script>
        <script src="{% static 'js/custom.js'%}"></script>


    </body>
</html>